#!/bin/bash
# 一次性提交代码，包括本地和服务器

if [ -n "$1" ]; then
    commit_message=$1
else
    echo "Commit message is required!"
    exit
fi

git status \
&& git add . \
&& git status \
&& git commit -m "$commit_message" \
&& git push origin main
